version: '3.6'

services:
  app_proxy:
    environment:
      APP_HOST: caboi-umbrel-flame_server
      APP_PORT: 5005

  server:
    image: pawelmalak/flame:2.3.1
    volumes:
      - ${APP_DATA_DIR}/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    environment:
      - PASSWORD=${APP_PASSWORD}
    restart: unless-stopped
